SELECT 
MEDIATOR_NUMBER,
COUNT_OF_MEDIATE,
DATE_OF_SUBMISSION,
DATE_OF_COMP,
MEDIATOR_CHANNEL,
PPMS_T_MEDIATOR.MEDIATOR_STATUS,
REQUEST_AMOUNT,
AMOUNT_END,
DISPUTE_ISSUE,
INSUR_TYPE,
END_DATE,
EXPERT_FEE,
PPMS_T_SPECIALIST.SALUTATION_NAME || ' ' || PPMS_T_SPECIALIST.FIRST_NAME || ' ' || PPMS_T_SPECIALIST.LAST_NAME as specialist,
"user".SALUTATION_NAME || ' ' || "user".FIRST_NAME || ' ' || "user".LAST_NAME as agent
FROM PPMS_T_MEDIATOR
LEFT JOIN PPMS_T_SPECIALIST ON PPMS_T_MEDIATOR.PPMS_T_SPECIALIST_ID = PPMS_T_SPECIALIST.ID
LEFT JOIN "user" ON PPMS_T_MEDIATOR.ASSIGNED_USER_ID = "user".ID
where DATE_OF_COMP between $P{start_date_time} and $P{end_date_time}
and $X{IN,DISPUTE_ISSUE,dispute_issue}
and $X{IN,INSUR_TYPE,insure_type}
and $X{IN,PPMS_T_MEDIATOR.MEDIATOR_STATUS,mediator_status}
and $X{IN,PPMS_T_MEDIATOR.PPMS_T_SPECIALIST_ID,specialist}
ORDER BY DATE_OF_COMP