SELECT 
sum(COUNT_OF_MEDIATE) AS total,
count(PPMS_T_MEDIATOR.ID) AS total_mediator,
SUM(EXPERT_FEE) AS total_fee,
PPMS_T_SPECIALIST.SALUTATION_NAME || ' ' || PPMS_T_SPECIALIST.FIRST_NAME || ' ' || PPMS_T_SPECIALIST.LAST_NAME as name
FROM PPMS_T_MEDIATOR
LEFT JOIN PPMS_T_SPECIALIST ON PPMS_T_MEDIATOR.PPMS_T_SPECIALIST_ID = PPMS_T_SPECIALIST.ID
WHERE PPMS_T_SPECIALIST_ID IS NOT NULL
and DATE_OF_COMP between $P{start_date_time} and $P{end_date_time} 
and $X{IN,PPMS_T_MEDIATOR.PPMS_T_SPECIALIST_ID,specialist}
GROUP BY PPMS_T_SPECIALIST.SALUTATION_NAME || ' ' || PPMS_T_SPECIALIST.FIRST_NAME || ' ' || PPMS_T_SPECIALIST.LAST_NAME
order by total_fee DESC