select
DATE_OF_CONSULT,
PPMS_T_CONSULT.SALUTATION_NAME || ' ' || PPMS_T_CONSULT.FIRST_NAME || ' ' || PPMS_T_CONSULT.LAST_NAME as name,
CONSULT_ID,
CHANNEL,
QUESTION,
PPMS_T_CONSULT.TYPE,
PPMS_T_CONSULT.STATUS,
PPMS_T_CONSULT.CONTACT_STATUS,
PPMS_T_CONSULT_INSURER_NAME.name as insurer_name,
"user".SALUTATION_NAME || ' ' || "user".FIRST_NAME || ' ' || "user".LAST_NAME as agent,
PPMS_T_DEPARTMENT.name AS department
from PPMS_T_CONSULT
left join PPMS_T_CONSULT_INSURER_NAME on PPMS_T_CONSULT.ID = PPMS_T_CONSULT_INSURER_NAME.PPMS_T_CONSULT_ID
LEFT JOIN "user" ON PPMS_T_CONSULT.ASSIGNED_USER_ID = "user".ID
LEFT JOIN PPMS_T_DEPARTMENT ON PPMS_T_CONSULT.DEPARTMENT_ID = PPMS_T_DEPARTMENT.ID
where DATE_OF_CONSULT between $P{start_date_time} and $P{end_date_time} 
and $X{IN,PPMS_T_DEPARTMENT.name,department}
and $X{IN,PPMS_T_CONSULT_INSURER_NAME.PPMS_T_INSURER_ID,insurer}
and $X{IN,PPMS_T_CONSULT.STATUS,consult_status}
and $X{IN,PPMS_T_CONSULT.TYPE,consult_type}
and $X{IN,PPMS_T_CONSULT.CONTACT_STATUS,contact_status}
order by DATE_OF_CONSULT