SELECT 
TO_CHAR(DATE_OF_COMP,'MM') as DATEMONTH,
CASE
    WHEN TO_CHAR(DATE_OF_COMP,'MM') = 01 THEN 'มกราคม'
    WHEN TO_CHAR(DATE_OF_COMP,'MM') = 02 THEN 'กุมภาพันธ์.'
    WHEN TO_CHAR(DATE_OF_COMP,'MM') = 03 THEN 'มีนาคม'
    WHEN TO_CHAR(DATE_OF_COMP,'MM') = 04 THEN 'เมษายน'
    WHEN TO_CHAR(DATE_OF_COMP,'MM') = 05 THEN 'พฤษภาคม'
    WHEN TO_CHAR(DATE_OF_COMP,'MM') = 06 THEN 'มิถุนายน'
    WHEN TO_CHAR(DATE_OF_COMP,'MM') = 07 THEN 'กรกฎาคม'
    WHEN TO_CHAR(DATE_OF_COMP,'MM')=  08 THEN 'สิงหาคม'
    WHEN TO_CHAR(DATE_OF_COMP,'MM') = 09 THEN 'กันยายน'
    WHEN TO_CHAR(DATE_OF_COMP,'MM') = 10 THEN 'ตุลาคม'
    WHEN TO_CHAR(DATE_OF_COMP,'MM') = 11 THEN 'พฤศจิกายน'
	WHEN TO_CHAR(DATE_OF_COMP,'MM') = 12 THEN 'ธันวาคม'    
END as monthfontthai,
TO_CHAR(DATE_OF_COMP,'YYYY') as DATEYEAR,
TO_CHAR(DATE_OF_COMP,'YYYY') + 543 AS thaiyear,
sum(COUNT_OF_MEDIATE) AS total,
count(PPMS_T_MEDIATOR.ID) AS total_mediator,
SUM(EXPERT_FEE) AS total_fee,
PPMS_T_SPECIALIST.SALUTATION_NAME || ' ' || PPMS_T_SPECIALIST.FIRST_NAME || ' ' || PPMS_T_SPECIALIST.LAST_NAME as name
FROM PPMS_T_MEDIATOR
LEFT JOIN PPMS_T_SPECIALIST ON PPMS_T_MEDIATOR.PPMS_T_SPECIALIST_ID = PPMS_T_SPECIALIST.ID
WHERE PPMS_T_SPECIALIST_ID IS NOT NULL
and TO_CHAR(DATE_OF_COMP,'MM') between TO_CHAR($P{start_date_time},'MM') and TO_CHAR($P{end_date_time},'MM')
and TO_CHAR(DATE_OF_COMP,'YYYY') between TO_CHAR($P{start_date_time},'YYYY') and TO_CHAR($P{end_date_time},'YYYY')
and $X{IN,PPMS_T_MEDIATOR.PPMS_T_SPECIALIST_ID,specialist}
GROUP BY TO_CHAR(DATE_OF_COMP,'YYYY'), TO_CHAR(DATE_OF_COMP,'MM'), PPMS_T_SPECIALIST.SALUTATION_NAME || ' ' || PPMS_T_SPECIALIST.FIRST_NAME || ' ' || PPMS_T_SPECIALIST.LAST_NAME
order by DATEYEAR, DATEMONTH, total_fee DESC